language: node_js
services:
  - postgresql
addons:
  postgresql: "9.6"
  apt:
    packages:
      - postgresql-9.6
      - postgresql-client-9.6
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE imenu_tdb;' -U postgres
  - sequelize db:migrate
  - sequelize db:seed:all
script: npm run test
after_success: 'npm run coverage'
