language: node_js
services:
  - postgresql
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE imenu_tedb;' -U postgres
  - psql -c "CREATE USER postgre WITH PASSWORD 'postgres';" -U postgres
script: npm run test
after_success: 'npm run coverage'
after_failure: 'cat /home/travis/.npm/_logs/2019-03-*-debug.log'
