language: node_js
addons:
  postgresql: "11.2"
  apt:
    packages:
      - postgresql-11.2
      - postgresql-client-11.2
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
services:
  - postgresql
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE imenu_test_db;' -U postgres
script: npm run test
after_success: 'npm run coverage'
