language: node_js
env:
  global:
    - NODE_ENV=test
    - SECRET_KEY=traeghiteslozae
    - PGPORT=5400
services:
  - postgresql
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE imenu_test_db;' -U postgres
script: npm run test
after_success: 'npm run coverage'
